### PR TITLE
Danihello/fact calls

### PR DESCRIPTION
**Pull request by danihello**
## What?

image

---
## Why?

adding the fact table which are the many calls

---
## How?

using dbt

---
## Testing?

---
## Screenshots (optional)

---

### CODE REVIEW

**Review by NikiforSokolov — DISMISSED** [review]
Looking good!

**Comment by danihello** [comment]
Hey looks like you didnt approve ?

**Review by NikiforSokolov — DISMISSED** [review]
Approving!

**Review by NikiforSokolov — APPROVED** [review]
Another try...

**Review by NikiforSokolov — APPROVED** [review]
Another one

**Review by NikiforSokolov — DISMISSED** [review]
approve

**Review by danihello — COMMENTED** [review]
s

**Comment by danihello** [comment]
seems the issue persist

**Review by NikiforSokolov — APPROVED** [review]
another approve (settings were changed)

**Pull request merged**
